//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lapscrap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EbayItem
    {
        public int Id { get; set; }
        public string ItemId { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string GalleryURL { get; set; }
        public string ViewItemURL { get; set; }
        public string postalCode { get; set; }
        public string Location { get; set; }
        public string Country { get; set; }
        public string ShippingServiceCost { get; set; }
        public string CurrentPrice { get; set; }
        public string TimeLeft { get; set; }
        public string ConditionId { get; set; }
        public string ConditionDisplayName { get; set; }
        public int LaptopId { get; set; }
    
        public virtual Laptop Laptop { get; set; }
    }
}
