//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lapscrap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Laptop()
        {
            this.EbayItem = new HashSet<EbayItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Brand { get; set; }
        public string Cpu { get; set; }
        public int Ram { get; set; }
        public float Size { get; set; }
        public string Resolution { get; set; }
        public string Gpu { get; set; }
        public int Hd { get; set; }
        public int Ssd { get; set; }
        public float Width { get; set; }
        public float Length { get; set; }
        public float Height { get; set; }
        public float Weight { get; set; }
        public int Battery { get; set; }
        public string Runtime { get; set; }
        public float Price { get; set; }
        public string Review_url { get; set; }
        public string Shop_url { get; set; }
        public string Ebay_url { get; set; }
        public string Video_Url { get; set; }
        public string Components { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EbayItem> EbayItem { get; set; }
    }
}
